name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Thank You For Making This issue - We Will Be Working On It Shortly.'
        pr-message: 'Thank You For Starting This Pull Request - We Will Be Reviewing It Shortly.'
